### ISSUE TITLE
Tutorial not producing images?

### ISSUE THREAD

**Issue by scho419** [sitzikbs/DeepFit#10]
Thank you for the great work!

I've ran the code for the tutorial and it doesn't seem to be producing any images - it only displays the values of the VBox. Is it supposed to produce any visuals when the notebook is ran?

**Comment by sitzikbs** [comment]
Yes. IpyVolume (ipv) produces an interactive figure that displays a 3D scatter plot of the points with a color overlay that you can rotate, zoom in etc. I suggest to check the package versions how you run the code (ipv had some constraints).
