### ISSUE TITLE
would you release the results or trained model of orientation normal estimation?

### ISSUE THREAD

**Issue by joycewangsy** [sitzikbs/DeepFit#2]
thank you very much for your attention.Can you provide a trained model or result about this?

**Comment by sitzikbs** [comment]
The trained model is available in the trained_models directory.

**Comment by joycewangsy** [comment]
thanks , the model is trained by orientation normal loss?

**Comment by sitzikbs** [comment]
If you mean oriented normals then the answer is no. It only provides unoriented normals since the method is local it is not possible to know the inside/outside direction. You can run other existing methods to determine orientation similar to PCPNet.
