### ISSUE TITLE
How can I estimate the z value of given (x,y) in fitted surface?

### ISSUE THREAD

**Issue by jinseok-karl** [sitzikbs/DeepFit#3]
Hi, thanks for sharing this great code.
Thanks to tutorial, I followed easily.
Then from fitted surface, did I estimate the z value of given (x,y) in fitted surface?
As you said, I would like putting (x,y) in n-jet.
But I can't go forward from this. How can I reach the goal?
Thanks

Best regard
Karl

**Comment by sitzikbs** [comment]
Not sure I understand the question. In 3D - you need to have x, y, z to estimate the n-jet. I recommend reading the paper and the original jet paper to fully understand how that works. 
If you mean how to estimate the z value given an estimated jet and x, y coordinates - You just plug it into the formula (equation 1 in Deepfit paper).
