### ISSUE TITLE
where is the DeepFit.SimpPointNet?

### ISSUE THREAD

**Issue by UestcJay** [sitzikbs/DeepFit#6]
Hi, thanks for your great work! 
I am a newbie in point cloud. I read your source code,  I  see `DeepFit.SimpPointNet` in the line 87 of  `test_c_est.py.`  I didn’t find it in the file `Deepfit.py`, Did I miss something?

**Comment by sitzikbs** [comment]
Thanks for picking this up. It should be `DeepFit.DeepFit`, same as in `test_n_est.py`. Before uploading, I refactored the code to have more meaningful names and missed this. 
Fixed it now.

**Comment by UestcJay** [comment]
> Thanks for picking this up. It should be `DeepFit.DeepFit`, same as in `test_n_est.py`. Before uploading, I refactored the code to have more meaningful names and missed this.
> Fixed it now.

thanks for your reply!  I don’t understand something， in `Deepfit.py`, does the return value `n_est` represent the normal direction of that point or the normal direction of the fitted surface?

**Comment by sitzikbs** [comment]
The normal vector of the fitted surface at that point.
