### ISSUE TITLE
conversion to surface mesh

### ISSUE THREAD

**Issue by jordandekraker** [sitzikbs/DeepFit#8]
Is there a lossless way to go from normals or other model outputs, for example here https://github.com/sitzikbs/DeepFit/blob/f19b83cbb7f669ed8ff73d1d204acd65ff6f9847/tutorial/compute_normals.py#L66
to a triangulated mesh?

**Comment by sitzikbs** [comment]
Sure. You are looking for a Surface Reconstruction algorithm (which is outside the scope of this repo). 
Several methods I recommend looking into: 
Poisson surface reconstruction (and screen poison surface reconstruction). 
DeepSDF, Occupancy networks, Neural splines, SAL, SALD, IGR. 

I personally like [SIREN](https://github.com/vsitzmann/siren), and their implementation. 

I have a current paper on the topic but it is not published yet so the code will be available only after publication.

**Comment by jordandekraker** [comment]
Great, thanks for the speedy reply! I'll check these out.
